"""
umlautsort.py : helps sort non-latin characters : Chip Calhoun
"""

import sys
import string

def alafiling(input):
	""" This function implements sort keys for non-latin characters according to ALA filing rules."""
	
	# key1: compare words and replace umlauts, etc.
	key1=input
	key1=key1.replace(u"\xC0", u"A") #Capital A-grave
	key1=key1.replace(u"\xE0", u"a") #Lowercase A-grave
	key1=key1.replace(u"\xC1", u"A") #Capital A-acute
	key1=key1.replace(u"\xE1", u"a") #Lowercase A-acute
	key1=key1.replace(u"\xC2", u"A") #Capital A-circumflex
	key1=key1.replace(u"\xE2", u"a") #Lowercase A-circumflex
	key1=key1.replace(u"\xC3", u"A") #Capital A-tilde
	key1=key1.replace(u"\xE3", u"a") #Lowercase A-tilde
	key1=key1.replace(u"\xC4", u"A") #Capital A-umlaut
	key1=key1.replace(u"\xE4", u"a") #Lowercase A-umlaut
	key1=key1.replace(u"\xC5", u"A") #Capital A-ring
	key1=key1.replace(u"\xE5", u"a") #Lowercase A-ring
	key1=key1.replace(u"\x100", u"A") #Capital A-macron
	key1=key1.replace(u"\x101", u"a") #Lowercase A-macron
	key1=key1.replace(u"\x102", u"A") #Capital A-breve
	key1=key1.replace(u"\x103", u"a") #Lowercase A-breve
	key1=key1.replace(u"\x104", u"A") #Capital A-ogonek
	key1=key1.replace(u"\x105", u"a") #Lowercase A-ogonek
	key1=key1.replace(u"\x1DE", u"A") #Capital A-diaeresis and macron
	key1=key1.replace(u"\x1DF", u"a") #Lowercase A-diaeresis and macron
	key1=key1.replace(u"\x1FA", u"A") #Capital A-acute ring
	key1=key1.replace(u"\x1FB", u"a") #Lowercase A-acute ring
	key1=key1.replace(u"\xC6", u"AE") #Capital AE Ligature
	key1=key1.replace(u"\xE6", u"ae") #Lowercase AE Ligature
	key1=key1.replace(u"\x1FC", u"AE") #Capital AE Ligature-acute
	key1=key1.replace(u"\x1FD", u"ae") #Lowercase AE Ligature-acute
	key1=key1.replace(u"\x1E02", u"B") #Capital B-dot
	key1=key1.replace(u"\x1E03", u"b") #Lowercase B-dot
	key1=key1.replace(u"\x106", u"C") #Capital C-acute
	key1=key1.replace(u"\x107", u"c") #Lowercase C-acute
	key1=key1.replace(u"\xC7", u"C") #Capital C-cedilla
	key1=key1.replace(u"\xE7", u"c") #Lowercase C-cedilla
	key1=key1.replace(u"\x10C", u"C") #Capital C-hachek
	key1=key1.replace(u"\x10D", u"c") #Lowercase C-hachek
	key1=key1.replace(u"\x108", u"C") #Capital C-circumflex
	key1=key1.replace(u"\x109", u"c") #Lowercase C-circumflex
	key1=key1.replace(u"\x10A", u"C") #Capital C-dot
	key1=key1.replace(u"\x10B", u"c") #Lowercase C-dot
	key1=key1.replace(u"\x1E10", u"D") #Capital D-cedilla
	key1=key1.replace(u"\x1E11", u"d") #Lowercase D-cedilla
	key1=key1.replace(u"\x10E", u"D") #Capital D-hachek
	key1=key1.replace(u"\x10F", u"d") #Lowercase D-hachek
	key1=key1.replace(u"\x1E0A", u"D") #Capital D-dot
	key1=key1.replace(u"\x1E0B", u"d") #Lowercase D-dot
	key1=key1.replace(u"\x110", u"D") #Capital D-stroke
	key1=key1.replace(u"\x111", u"d") #Lowercase D-stroke
	key1=key1.replace(u"\xD0", u"D") #Capital Eth (Icelandic)
	key1=key1.replace(u"\xF0", u"d") #Lowercase Eth (Icelandic)
	key1=key1.replace(u"\x1F1", u"DZ") #Capital DZ Ligature
	key1=key1.replace(u"\x1F2", u"DZ") #Capital Dz Ligature
	key1=key1.replace(u"\x1F3", u"dz") #Lowercase DZ Ligature
	key1=key1.replace(u"\x1C4", u"DZ") #Capital DZ-hachek
	key1=key1.replace(u"\x1C5", u"DZ") #Capital Dz-hachek
	key1=key1.replace(u"\x1C6", u"dz") #Lowercase DZ-hachek
	key1=key1.replace(u"\xC8", u"E") #Capital E-grave
	key1=key1.replace(u"\xE8", u"e") #Lowercase E-grave
	key1=key1.replace(u"\xC9", u"E") #Capital E-acute
	key1=key1.replace(u"\xE9", u"e") #Lowercase E-acute
	key1=key1.replace(u"\x11A", u"E") #Capital E-hachek
	key1=key1.replace(u"\x11B", u"e") #Lowercase E-hachek
	key1=key1.replace(u"\xCA", u"E") #Capital E-circumflex
	key1=key1.replace(u"\xEA", u"e") #Lowercase E-circumflex
	key1=key1.replace(u"\xCB", u"E") #Capital E-umlaut
	key1=key1.replace(u"\xEB", u"e") #Lowercase E-umlaut
	key1=key1.replace(u"\x112", u"E") #Capital E-macron
	key1=key1.replace(u"\x113", u"e") #Lowercase E-macron
	key1=key1.replace(u"\x114", u"E") #Capital E-breve
	key1=key1.replace(u"\x115", u"e") #Lowercase E-breve
	key1=key1.replace(u"\x118", u"E") #Capital E-ogonek
	key1=key1.replace(u"\x119", u"e") #Lowercase E-ogonek
	key1=key1.replace(u"\x116", u"E") #Capital E-dot
	key1=key1.replace(u"\x117", u"e") #Lowercase E-dot
	key1=key1.replace(u"\x1B7", u"E") #Capital Ezh
	key1=key1.replace(u"\x292", u"e") #Lowercase Ezh
	key1=key1.replace(u"\x1EE", u"E") #Capital Ezh-hachek
	key1=key1.replace(u"\x1EF", u"e") #Lowercase Ezh-hachek
	key1=key1.replace(u"\x1E1E", u"F") #Capital F-dot
	key1=key1.replace(u"\x1E1F", u"f") #Lowercase F-dot
	key1=key1.replace(u"\x192", u"f") #Lowercase F-hook
	key1=key1.replace(u"\xFB00", u"ff") #Lowercase FF Ligature
	key1=key1.replace(u"\xFB01", u"fi") #Lowercase FI Ligature
	key1=key1.replace(u"\xFB02", u"fl") #Lowercase FL Ligature
	key1=key1.replace(u"\xFB03", u"ffi") #Lowercase FFI Ligature
	key1=key1.replace(u"\xFB04", u"ffl") #Lowercase FFL Ligature
	key1=key1.replace(u"\xFB05", u"ft") #Lowercase FT Ligature
	key1=key1.replace(u"\x1F4", u"G") #Capital G-acute
	key1=key1.replace(u"\x1F5", u"g") #Lowercase G-acute
	key1=key1.replace(u"\x122", u"G") #Capital G-cedilla
	key1=key1.replace(u"\x123", u"g") #Lowercase G-cedilla
	key1=key1.replace(u"\x1E6", u"G") #Capital G-hachek
	key1=key1.replace(u"\x1E7", u"g") #Lowercase G-hachek
	key1=key1.replace(u"\x11C", u"G") #Capital G-circumflex
	key1=key1.replace(u"\x11D", u"g") #Lowercase G-circumflex
	key1=key1.replace(u"\x11E", u"G") #Capital G-breve
	key1=key1.replace(u"\x11F", u"g") #Lowercase G-breve
	key1=key1.replace(u"\x120", u"G") #Capital G-dot
	key1=key1.replace(u"\x121", u"g") #Lowercase G-dot
	key1=key1.replace(u"\x1E4", u"G") #Capital G-stroke
	key1=key1.replace(u"\x1E5", u"g") #Lowercase G-stroke
	key1=key1.replace(u"\x124", u"H") #Capital H-circumflex
	key1=key1.replace(u"\x125", u"h") #Lowercase H-circumflex
	key1=key1.replace(u"\x126", u"H") #Capital H-stroke
	key1=key1.replace(u"\x127", u"h") #Lowercase H-stroke
	key1=key1.replace(u"\xCC", u"I") #Capital I-grave
	key1=key1.replace(u"\xEC", u"I") #Lowercase I-grave
	key1=key1.replace(u"\xCD", u"I") #Capital I-acute
	key1=key1.replace(u"\xED", u"I") #Lowercase I-acute
	key1=key1.replace(u"\xCE", u"I") #Capital I-circumflex
	key1=key1.replace(u"\xEE", u"I") #Lowercase I-circumflex
	key1=key1.replace(u"\x128", u"I") #Capital I-tilde
	key1=key1.replace(u"\x129", u"I") #Lowercase I-tilde
	key1=key1.replace(u"\xCF", u"I") #Capital I-umlaut
	key1=key1.replace(u"\xEF", u"I") #Lowercase I-umlaut
	key1=key1.replace(u"\x12A", u"I") #Capital I-macron
	key1=key1.replace(u"\x12B", u"I") #Lowercase I-macron
	key1=key1.replace(u"\x12C", u"I") #Capital I-breve
	key1=key1.replace(u"\x12D", u"I") #Lowercase I-breve
	key1=key1.replace(u"\x12E", u"I") #Capital I-ogonek
	key1=key1.replace(u"\x12F", u"I") #Lowercase I-ogonek
	key1=key1.replace(u"\x130", u"I") #Capital I-dot
	key1=key1.replace(u"\x131", u"I") #Lowercase I-dotless
	key1=key1.replace(u"\x132", u"IJ") #Capital IJ Ligature
	key1=key1.replace(u"\x133", u"ij") #Lowercase IJ Ligature
	key1=key1.replace(u"\x134", u"J") #Capital J-circumflex
	key1=key1.replace(u"\x135", u"j") #Lowercase J-circumflex
	key1=key1.replace(u"\x1E30", u"K") #Capital K-acute
	key1=key1.replace(u"\x1E31", u"k") #Lowercase K-acute
	key1=key1.replace(u"\x136", u"K") #Capital K-cedilla
	key1=key1.replace(u"\x137", u"k") #Lowercase K-cedilla
	key1=key1.replace(u"\x1E8", u"K") #Capital K-hachek
	key1=key1.replace(u"\x1E9", u"k") #Lowercase K-hachek
	key1=key1.replace(u"\x138", u"K") #Small Capital K
	key1=key1.replace(u"\x139", u"L") #Capital L-acute
	key1=key1.replace(u"\x13A", u"l") #Lowercase L-acute
	key1=key1.replace(u"\x13B", u"L") #Capital L-cedilla
	key1=key1.replace(u"\x13C", u"l") #Lowercase L-cedilla
	key1=key1.replace(u"\x13D", u"L") #Capital L-hachek
	key1=key1.replace(u"\x13E", u"l") #Lowercase L-hachek
	key1=key1.replace(u"\x13F", u"L") #Capital L-middle dot
	key1=key1.replace(u"\x140", u"l") #Lowercase L-middle dot
	key1=key1.replace(u"\x141", u"L") #Capital L-stroke
	key1=key1.replace(u"\x142", u"l") #Lowercase L-stroke
	key1=key1.replace(u"\x1C7", u"LJ") #Capital LJ Ligature
	key1=key1.replace(u"\x1C8", u"LJ") #Capital Lj Ligature
	key1=key1.replace(u"\x1C9", u"lj") #Lowercase LJ Ligature
	key1=key1.replace(u"\x1E40", u"M") #Capital M-dot
	key1=key1.replace(u"\x1E41", u"m") #Lowercase M-dot
	key1=key1.replace(u"\x143", u"N") #Capital N-acute
	key1=key1.replace(u"\x144", u"n") #Lowercase N-acute
	key1=key1.replace(u"\x145", u"N") #Capital N-cedilla
	key1=key1.replace(u"\x146", u"n") #Lowercase N-cedilla
	key1=key1.replace(u"\x147", u"N") #Capital N-hachek
	key1=key1.replace(u"\x148", u"n") #Lowercase N-hachek
	key1=key1.replace(u"\xD1", u"N") #Capital N-tilde
	key1=key1.replace(u"\xF1", u"n") #Lowercase N-tilde
	key1=key1.replace(u"\x149", u"n") #Lowercase N-apostrophe (before)
	key1=key1.replace(u"\x14A", u"N") #Capital Eng
	key1=key1.replace(u"\x14B", u"n") #Lowercase Eng
	key1=key1.replace(u"\x1CA", u"NJ") #Capital NJ Ligature
	key1=key1.replace(u"\x1CB", u"NJ") #Capital Nj Ligature
	key1=key1.replace(u"\x1CC", u"nj") #Lowercase NJ Ligature
	key1=key1.replace(u"\xD2", u"O") #Capital O-grave
	key1=key1.replace(u"\xF2", u"o") #Lowercase O-grave
	key1=key1.replace(u"\xD3", u"O") #Capital O-acute
	key1=key1.replace(u"\xF3", u"o") #Lowercase O-acute
	key1=key1.replace(u"\xD4", u"O") #Capital O-circumflex
	key1=key1.replace(u"\xF4", u"o") #Lowercase O-circumflex
	key1=key1.replace(u"\xD5", u"O") #Capital O-tilde
	key1=key1.replace(u"\xF5", u"o") #Lowercase O-tilde
	key1=key1.replace(u"\xD6", u"O") #Capital O-umlaut
	key1=key1.replace(u"\xF6", u"o") #Lowercase O-umlaut
	key1=key1.replace(u"\x14C", u"O") #Capital O-macron
	key1=key1.replace(u"\x14D", u"o") #Lowercase O-macron
	key1=key1.replace(u"\x14E", u"O") #Capital O-breve
	key1=key1.replace(u"\x14F", u"o") #Lowercase O-breve
	key1=key1.replace(u"\xD8", u"O") #Capital O-slash
	key1=key1.replace(u"\xF8", u"o") #Lowercase O-slash
	key1=key1.replace(u"\x150", u"O") #Capital O-double acute
	key1=key1.replace(u"\x151", u"o") #Lowercase O-double acute
	key1=key1.replace(u"\x1FE", u"O") #Capital O-acute slash
	key1=key1.replace(u"\x1FF", u"o") #Lowercase O-acute slash
	key1=key1.replace(u"\x152", u"OE") #Capital OE Ligature
	key1=key1.replace(u"\x153", u"oe") #Lowercase OE Ligature
	key1=key1.replace(u"\x1E56", u"P") #Capital P-dot
	key1=key1.replace(u"\x1E57", u"p") #Lowercase P-dot
	key1=key1.replace(u"\x154", u"R") #Capital R-acute
	key1=key1.replace(u"\x155", u"r") #Lowercase R-acute
	key1=key1.replace(u"\x156", u"R") #Capital R-cedilla
	key1=key1.replace(u"\x157", u"r") #Lowercase R-cedilla
	key1=key1.replace(u"\x158", u"R") #Capital R-hachek
	key1=key1.replace(u"\x159", u"r") #Lowercase R-hachek
	key1=key1.replace(u"\x27C", u"r") #Lowercase R-Long leg
	key1=key1.replace(u"\x15A", u"S") #Capital S-acute
	key1=key1.replace(u"\x15B", u"s") #Lowercase S-acute
	key1=key1.replace(u"\x15E", u"S") #Capital S-cedilla
	key1=key1.replace(u"\x15F", u"s") #Lowercase S-cedilla
	key1=key1.replace(u"\x160", u"S") #Capital S-hachek
	key1=key1.replace(u"\x161", u"s") #Lowercase S-hachek
	key1=key1.replace(u"\x15C", u"S") #Capital S-circumflex
	key1=key1.replace(u"\x15D", u"s") #Lowercase S-circumflex
	key1=key1.replace(u"\x1E60", u"S") #Capital S-dot
	key1=key1.replace(u"\x1E61", u"s") #Lowercase S-dot
	key1=key1.replace(u"\x17F", u"s") #Lowercase S-long
	key1=key1.replace(u"\xDF", u"ss") #Lowercase SZ Ligature
	key1=key1.replace(u"\x162", u"T") #Capital T-cedilla
	key1=key1.replace(u"\x163", u"t") #Lowercase T-cedilla
	key1=key1.replace(u"\x164", u"T") #Capital T-hachek
	key1=key1.replace(u"\x165", u"t") #Lowercase T-hachek
	key1=key1.replace(u"\x1E6A", u"T") #Capital T-dot
	key1=key1.replace(u"\x1E6B", u"t") #Lowercase T-dot
	key1=key1.replace(u"\x166", u"T") #Capital T-stroke
	key1=key1.replace(u"\x167", u"t") #Lowercase T-stroke
	key1=key1.replace(u"\xDE", u"ZZ") #Capital Thorn
	key1=key1.replace(u"\xFE", u"zz") #Lowercase Thorn
	key1=key1.replace(u"\xD9", u"U") #Capital U-grave
	key1=key1.replace(u"\xF9", u"u") #Lowercase U-grave
	key1=key1.replace(u"\xDA", u"U") #Capital U-acute
	key1=key1.replace(u"\xFA", u"u") #Lowercase U-acute
	key1=key1.replace(u"\xDB", u"U") #Capital U-circumflex
	key1=key1.replace(u"\xFB", u"u") #Lowercase U-circumflex
	key1=key1.replace(u"\x168", u"U") #Capital U-tilde
	key1=key1.replace(u"\x169", u"u") #Lowercase U-tilde
	key1=key1.replace(u"\xDC", u"U") #Capital U-umlaut
	key1=key1.replace(u"\xFC", u"u") #Lowercase U-umlaut
	key1=key1.replace(u"\x16E", u"U") #Capital U-ring
	key1=key1.replace(u"\x16F", u"u") #Lowercase U-ring
	key1=key1.replace(u"\x16A", u"U") #Capital U-macron
	key1=key1.replace(u"\x16B", u"u") #Lowercase U-macron
	key1=key1.replace(u"\x16C", u"U") #Capital U-breve
	key1=key1.replace(u"\x16D", u"u") #Lowercase U-breve
	key1=key1.replace(u"\x172", u"U") #Capital U-ogonek
	key1=key1.replace(u"\x173", u"u") #Lowercase U-ogonek
	key1=key1.replace(u"\x170", u"U") #Capital U-double acute
	key1=key1.replace(u"\x171", u"u") #Lowercase U-double acute
	key1=key1.replace(u"\x1E80", u"W") #Capital W-grave
	key1=key1.replace(u"\x1E81", u"w") #Lowercase W-grave
	key1=key1.replace(u"\x1E82", u"W") #Capital W-acute
	key1=key1.replace(u"\x1E83", u"w") #Lowercase W-acute
	key1=key1.replace(u"\x174", u"W") #Capital W-circumflex
	key1=key1.replace(u"\x175", u"w") #Lowercase W-circumflex
	key1=key1.replace(u"\x1E84", u"W") #Capital W-umlaut
	key1=key1.replace(u"\x1E85", u"w") #Lowercase W-umlaut
	key1=key1.replace(u"\x1EF2", u"Y") #Capital Y-grave
	key1=key1.replace(u"\x1EF3", u"y") #Lowercase Y-grave
	key1=key1.replace(u"\xDD", u"Y") #Capital Y-acute
	key1=key1.replace(u"\xFD", u"y") #Lowercase Y-acute
	key1=key1.replace(u"\x176", u"Y") #Capital Y-circumflex
	key1=key1.replace(u"\x177", u"y") #Lowercase Y-circumflex
	key1=key1.replace(u"\x9F", u"Y") #Capital Y-umlaut
	key1=key1.replace(u"\xFF", u"y") #Lowercase Y-umlaut
	key1=key1.replace(u"\x179", u"Z") #Capital Z-acute
	key1=key1.replace(u"\x17A", u"z") #Lowercase Z-acute
	key1=key1.replace(u"\x17D", u"Z") #Capital Z-hachek
	key1=key1.replace(u"\x17E", u"z") #Lowercase Z-hachek
	key1=key1.replace(u"\x17B", u"Z") #Capital Z-dot
	key1=key1.replace(u"\x17C", u"z") #Lowercase Z-dot

	# key2: sort the lowercase word before the uppercase word and sort
	# the word with umlaut after the word without umlaut
	key2=input.swapcase()
	
	# in case two words are the same according to key1, sort the words
	# according to key2. 
	return (key1, key2)
 
#
